In [2]:
import pandas as pd

In [6]:
df1=pd.read_csv('../../combined_datasets/hate_speech_cleaned.csv')

In [7]:
df1

      Unnamed: 0                                              tweet
0              0  राहुल गांधी ने दावा करते हुए कहा कि सरकार बनेग...
1              1  देश के युवा ने अपने दिल की बात बोलनी शुरू कर द...
2              2  अच्छा हुआ योगी अयोध्या से चुनाव नहीं लड़े उन्ह...
3              3  में नेता ने फिर उगला जहर बोले फिर बाबर जैसा रा...
4              4  और सपा के दिमाग मे केवल एक ही जाति है बाकी जात...
...          ...                                                ...
2209        2209  गठबन्धन लाइ भोट हालेर जिताउनु भनेको देश दुर्घट...
2210        2210  यत्रो समय सम्म नेपालले राजनीति कर्मीको छाँटकाट...
2211        2211  नेपालको वर्तमान संविधान अनुसार संसद भंग हुन सक...
2212        2212  भरतपुरमा हुने रेणु दाहाल जिताउ चुनावि सभामा गग...
2213        2213  राणाले १०४ वर्ष लुटे ३० वर्ष पञ्चायतले लुट्यो ...

[2214 rows x 2 columns]

In [8]:
df2=pd.read_csv('../../combined_datasets/augmented_hindi.csv')

In [9]:
df2

,original_text,augmented_text,similarity
0,राहुल गांधी ने दावा करते हुए कहा कि सरकार बनेग...,गांधी जी ने दावा किया कि सरकार कांग्रेस पार्टी...,0.998994
1,देश के युवा ने अपने दिल की बात बोलनी शुरू कर द...,देश के युवाओं ने अपना हृदय बोलना शुरू कर दिया ...,0.999504
2,अच्छा हुआ योगी अयोध्या से चुनाव नहीं लड़े उन्ह...,योगी अयोध्या से चुनाव नहीं लड़ते थे। उन्हें रा...,0.998435
3,में नेता ने फिर उगला जहर बोले फिर बाबर जैसा रा...,"फिर उसने कहा, ""यह राज्य वैसा ही होगा जैसे बाबे...",0.996888
4,और सपा के दिमाग मे केवल एक ही जाति है बाकी जात...,और सापा के मन में केवल एक जाति है और उनके हृदय...,0.998988
...,...,...,...
669,हाथरस की बेटी को न्याय तभी मिलेगा जब उत्तर प्र...,रस की बेटी को न्याय तभी मिलेगा जब उत्तर प्रदेश...,0.999602
670,इस्तीफे के बाद मौर्य का बड़ा बयान मेरा इस्तीफ़...,इस त्यागपत्र के बाद मौर्य का बड़ा वक्तव्य हैः ...,0.998748
671,अखिलेश जी को अपना नाम श्री अखिलेश अली जिन्ना र...,श्री अखलीखान को स्वयं श्री अखलीखान अली जिन्ना ...,0.996486
672,जनता का रुख़ साफ़ है इस बार भाजपा साफ़ है,जनता का हित स्पष्ट है. इस बार भाजपा स्पष्ट है.,0.995555
673,स्वामी प्रसाद मौर्य कई विधायकों संग सपा में शा...,सभा में शामिल बहुत से सांसदों में से एक प्रसाद...,0.998382

In [19]:
df2['label']=1

In [20]:
df2.rename(columns={'augmented_text':'tweet'},inplace=True)

In [21]:
df2=df2[['tweet','label']]

In [22]:
df2

                                                 tweet  label
0    गांधी जी ने दावा किया कि सरकार कांग्रेस पार्टी...      1
1    देश के युवाओं ने अपना हृदय बोलना शुरू कर दिया ...      1
2    योगी अयोध्या से चुनाव नहीं लड़ते थे। उन्हें रा...      1
3    फिर उसने कहा, "यह राज्य वैसा ही होगा जैसे बाबे...      1
4    और सापा के मन में केवल एक जाति है और उनके हृदय...      1
..                                                 ...    ...
669  रस की बेटी को न्याय तभी मिलेगा जब उत्तर प्रदेश...      1
670  इस त्यागपत्र के बाद मौर्य का बड़ा वक्तव्य हैः ...      1
671  श्री अखलीखान को स्वयं श्री अखलीखान अली जिन्ना ...      1
672     जनता का हित स्पष्ट है. इस बार भाजपा स्पष्ट है.      1
673  सभा में शामिल बहुत से सांसदों में से एक प्रसाद...      1

[674 rows x 2 columns]

In [10]:
df3=pd.read_csv('../../combined_datasets/augmented_nepali.csv')

In [11]:
df3

,original_text,augmented_text,similarity
0,म न कसैको बिरोधी त कसैको वकालत गरिरहेकों छु। त...,यदि तपाईँ वास्तवमै देशलाई प्रेम गर्न चाहनुहुन्...,0.996225
1,तिनै मण्डललेहरु अहिले ठेक्कातन्त्र चलाउदै राजा...,सभाहरू राजालाई खोजिरहेका छन्। तिनीहरूले भनिरहे...,0.996918
2,१७ हजारे संगै पछि लागेका भन्दै काे हुन झोले ।,यो १७ वर्ष पछि भएको जस्तो देखिन्छ ।,0.995612
3,दोहोरो नागरिकतामा लामिछानेलाई सरकारले थप कारबा...,"सरकारले दुइविध नागरिकता भएका नागरिकहरूलाई, चाह...",0.997907
4,छुट्या रहेछ तर थाहा पाए। केटाकेटी र मट्याङ्ग्र...,सार्वजनिक स्वास्थ्य र क्लिनिकल उपायका लागि पीस...,0.996858
...,...,...,...
1530,गठबन्धन लाइ भोट हालेर जिताउनु भनेको देश दुर्घट...,एउटा मत जित्नको लागि коалицияले एउटा देशलाई सम...,0.997335
1531,यत्रो समय सम्म नेपालले राजनीति कर्मीको छाँटकाट...,नेपालले राजनैतिक अधिकारकर्मीहरूको दृश्य देखेर ...,0.997667
1532,नेपालको वर्तमान संविधान अनुसार संसद भंग हुन सक...,हालको नेपाली संविधानका अनुसार संसदलाई विघटन गर...,0.998508
1533,भरतपुरमा हुने रेणु दाहाल जिताउ चुनावि सभामा गग...,"भारतपुर, गेन थापा र विश्वप्रकाश रेनु शक्ति जिट...",0.998451
1534,राणाले १०४ वर्ष लुटे ३० वर्ष पञ्चायतले लुट्यो ...,"Rana ले १०४ वर्ष लुटेका थिए, Panchai ले ३० वर्...",0.997794

In [12]:
df3['label']=1

In [13]:
df3.columns

Index(['original_text', 'augmented_text', 'similarity', 'label'], dtype='object')

In [15]:
df3.rename(columns={'augmented_text':'tweet'},inplace=True)

In [16]:
df3.columns

Index(['original_text', 'tweet', 'similarity', 'label'], dtype='object')

In [17]:
df3=df3[['tweet','label']]

In [18]:
df3

                                                  tweet  label
0     यदि तपाईँ वास्तवमै देशलाई प्रेम गर्न चाहनुहुन्...      1
1     सभाहरू राजालाई खोजिरहेका छन्। तिनीहरूले भनिरहे...      1
2                   यो १७ वर्ष पछि भएको जस्तो देखिन्छ ।      1
3     सरकारले दुइविध नागरिकता भएका नागरिकहरूलाई, चाह...      1
4     सार्वजनिक स्वास्थ्य र क्लिनिकल उपायका लागि पीस...      1
...                                                 ...    ...
1530  एउटा मत जित्नको लागि коалицияले एउटा देशलाई सम...      1
1531  नेपालले राजनैतिक अधिकारकर्मीहरूको दृश्य देखेर ...      1
1532  हालको नेपाली संविधानका अनुसार संसदलाई विघटन गर...      1
1533  भारतपुर, गेन थापा र विश्वप्रकाश रेनु शक्ति जिट...      1
1534  Rana ले १०४ वर्ष लुटेका थिए, Panchai ले ३० वर्...      1

[1535 rows x 2 columns]

In [23]:
combined_df=pd.concat([df2,df3],ignore_index=True)

In [25]:
combined_df.to_csv("../../combined_datasets/final_augmented_dataset.csv", index=False)

In [26]:
## combining with original dataset

In [27]:
df_original=pd.read_csv('../../chipsal-datasets/train/task2.csv')

In [29]:
df_original

       index                                              tweet  label
0      10001  अमर उजाला दैनिक समाचार में हेड लाइन में प्रकाश...      0
1      10002  बीजेपी @BJP4India केन्द्रीय चुनाव समिति की मीट...      0
2      10003  #AssemblyElections2022 प्रभारी निरीक्षक गौर श्...      0
3      10004  #ब्रेकिंग - मध्यप्रदेश सीहोर में हैवानियत 10 स...      0
4      10006  #AmitShah ने कहा उत्तर प्रदेश में पूर्ववर्ती स...      0
...      ...                                                ...    ...
19014  37164  नेपालको वर्तमान संविधान अनुसार संसद भंग हुन सक...      1
19015  37165  भरतपुरमा हुने रेणु दाहाल जिताउ चुनावि सभामा "ग...      1
19016  37166  साधारण नेपाली  जनता बसन्त घिमिरे ले बालेनले चु...      0
19017  37169  राणाले १०४ वर्ष लुटे\n३० वर्ष पञ्चायतले लुट्यो...      1
19018  37170  ओलि फेर्न नसक्ने एमाले, देउवा फेर्न नसक्ने काङ...      0

[19019 rows x 3 columns]

In [30]:
df_original=df_original[['tweet','label']]

In [33]:
df_original

                                                   tweet  label
0      अमर उजाला दैनिक समाचार में हेड लाइन में प्रकाश...      0
1      बीजेपी @BJP4India केन्द्रीय चुनाव समिति की मीट...      0
2      #AssemblyElections2022 प्रभारी निरीक्षक गौर श्...      0
3      #ब्रेकिंग - मध्यप्रदेश सीहोर में हैवानियत 10 स...      0
4      #AmitShah ने कहा उत्तर प्रदेश में पूर्ववर्ती स...      0
...                                                  ...    ...
19014  नेपालको वर्तमान संविधान अनुसार संसद भंग हुन सक...      1
19015  भरतपुरमा हुने रेणु दाहाल जिताउ चुनावि सभामा "ग...      1
19016  साधारण नेपाली  जनता बसन्त घिमिरे ले बालेनले चु...      0
19017  राणाले १०४ वर्ष लुटे\n३० वर्ष पञ्चायतले लुट्यो...      1
19018  ओलि फेर्न नसक्ने एमाले, देउवा फेर्न नसक्ने काङ...      0

[19019 rows x 2 columns]

In [34]:
combined_df

                                                  tweet  label
0     गांधी जी ने दावा किया कि सरकार कांग्रेस पार्टी...      1
1     देश के युवाओं ने अपना हृदय बोलना शुरू कर दिया ...      1
2     योगी अयोध्या से चुनाव नहीं लड़ते थे। उन्हें रा...      1
3     फिर उसने कहा, "यह राज्य वैसा ही होगा जैसे बाबे...      1
4     और सापा के मन में केवल एक जाति है और उनके हृदय...      1
...                                                 ...    ...
2204  एउटा मत जित्नको लागि коалицияले एउटा देशलाई सम...      1
2205  नेपालले राजनैतिक अधिकारकर्मीहरूको दृश्य देखेर ...      1
2206  हालको नेपाली संविधानका अनुसार संसदलाई विघटन गर...      1
2207  भारतपुर, गेन थापा र विश्वप्रकाश रेनु शक्ति जिट...      1
2208  Rana ले १०४ वर्ष लुटेका थिए, Panchai ले ३० वर्...      1

[2209 rows x 2 columns]

In [43]:
df_final=pd.concat([df_original,combined_df],ignore_index=True)

In [44]:
df_final

                                                   tweet  label
0      अमर उजाला दैनिक समाचार में हेड लाइन में प्रकाश...      0
1      बीजेपी @BJP4India केन्द्रीय चुनाव समिति की मीट...      0
2      #AssemblyElections2022 प्रभारी निरीक्षक गौर श्...      0
3      #ब्रेकिंग - मध्यप्रदेश सीहोर में हैवानियत 10 स...      0
4      #AmitShah ने कहा उत्तर प्रदेश में पूर्ववर्ती स...      0
...                                                  ...    ...
21223  एउटा मत जित्नको लागि коалицияले एउटा देशलाई सम...      1
21224  नेपालले राजनैतिक अधिकारकर्मीहरूको दृश्य देखेर ...      1
21225  हालको नेपाली संविधानका अनुसार संसदलाई विघटन गर...      1
21226  भारतपुर, गेन थापा र विश्वप्रकाश रेनु शक्ति जिट...      1
21227  Rana ले १०४ वर्ष लुटेका थिए, Panchai ले ३० वर्...      1

[21228 rows x 2 columns]

In [45]:
df_final.columns

Index(['tweet', 'label'], dtype='object')

In [47]:
df_final

                                                   tweet  label
0      अमर उजाला दैनिक समाचार में हेड लाइन में प्रकाश...      0
1      बीजेपी @BJP4India केन्द्रीय चुनाव समिति की मीट...      0
2      #AssemblyElections2022 प्रभारी निरीक्षक गौर श्...      0
3      #ब्रेकिंग - मध्यप्रदेश सीहोर में हैवानियत 10 स...      0
4      #AmitShah ने कहा उत्तर प्रदेश में पूर्ववर्ती स...      0
...                                                  ...    ...
21223  एउटा मत जित्नको लागि коалицияले एउटा देशलाई सम...      1
21224  नेपालले राजनैतिक अधिकारकर्मीहरूको दृश्य देखेर ...      1
21225  हालको नेपाली संविधानका अनुसार संसदलाई विघटन गर...      1
21226  भारतपुर, गेन थापा र विश्वप्रकाश रेनु शक्ति जिट...      1
21227  Rana ले १०४ वर्ष लुटेका थिए, Panchai ले ३० वर्...      1

[21228 rows x 2 columns]

In [48]:
df_final.to_csv("../../combined_datasets/final_combined_dataset.csv", index=False)